name: kylemcase
favicon: null
layout_spectrum: 0.292138779303059
typography_spectrum: 0.20265201642178
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8955314254853874
  lightness: 0.3367241134401411
  saturation: 0.2304176890756935
  rhythmicContrast: 0.34374823118560016
purpose: []
