name: kylemcase
favicon: null
layout_spectrum: 0
typography_spectrum: 0.48885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171813'
    - '#ead994'
    - '#4d4835'
    - '#9dcaff'
    - '#ff3f38'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
