name: kylemcase
favicon: null
layout_spectrum: 0.27145
typography_spectrum: 0.48885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03020a'
    - '#b3edff'
    - '#9f7bff'
    - '#5b52ff'
    - '#113498'
  brandStrength: 0.8955314254853874
  lightness: 0.3367241134401411
  saturation: 0.2304176890756935
  rhythmicContrast: 0.34374823118560016
purpose: []
